export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

export const ORDER_ADD_BURGER = 'ORDER_ADD_BURGER';
export const ORDER_REMOVE_BURGER = 'ORDER_REMOVE_BURGER';

export const BURGER_ADD_INGREDIENT = 'BURGER_ADD_INGREDIENT';
export const BURGER_REMOVE_INGREDIENT = 'BURGER_REMOVE_INGREDIENT';
export const BURGER_CLEAR_INGREDIENTS = 'BURGER_CLEAR_INGREDIENTS';
export const BURGER_SET_INGREDINETS = 'BURGER_SET_INGREDINETS';

export const BURGER_SET_BREAD = 'BURGER_SET_BREAD';
export const BURGER_SET_MEAT = 'BURGER_SET_MEAT';
export const BURGER_CHANGE_BREAD_MID = 'BURGER_CHANGE_BREAD_MID';

export const BURGER_NEXT_PHASE = 'BURGER_NEXT_PHASE';
export const BURGER_PREVIOUS_PHASE = 'BURGER_PREVIOUS_PHASE';